### PR TITLE
pool: Decrement ._opened_conns when connect() raises exception

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by eventlistener** [comment]
@methane Hi! May I ask why this doesn't get merged?

**Comment by methane** [comment]
see https://github.com/PyMySQL/Tornado-MySQL#warning

**Comment by ycraaron** [comment]
I think this should be merged to master because it's not a new feature instead it's a bug related to max_open_connections. Here is the problem I have related to this pr. After reading the code and figuring out the problem, I find this pr, which I think is a good fix for it, hope this could be merged to master.
https://github.com/AmbiLabs/Tornado-MySQL/issues/1

**Comment by methane** [comment]
I'll merge this this time, but please don't expect I fix more bugs anymore.
I strongly recommend you to Go asyncio.

**Comment by ycraaron** [comment]
Thanks, bro! 
Our problems seem to be more complicated for the time being and Tornado-MySQL is a good choice.
Yeah, we will explore the asyncio, thanks for this merge!

**Pull request merged**
