### PR TITLE
Set connect_timeout for socket.

### LINKED ISSUE #23: Handle connect_timeout
Leaving it here, cause it took me a while to understand why my connections aren't dropping faster if I use low connect_timeout. From https://github.com/PyMySQL/Tornado-MySQL/blob/master/tornado_mysql/connections.py#L792 

``` python
stream = iostream.IOStream(sock)
# TODO: handle connect_timeout
yield stream.connect(addr)
```

### PR DESCRIPTION
**Pull request by kerma**
Attepts to fix #23 by passing connect_timeout parameter to
socket.settimeout(). After connection is established restores
the default behaviour, so that next operations on connection
would not be affected by the socket timeout.

Sorry about the PEP8 autoformat, I can revert those chucks if you prefer so.
Relevant change is in: https://github.com/PyMySQL/Tornado-MySQL/compare/master...kerma:master#diff-15862cb89b51435589a93cef62c145b3R797

### CODE REVIEW

**Comment by methane** [comment]
Have you really tested your code works?

I think `sock.settimeout` is not able to used with Tornado.
[with_timeout](http://www.tornadoweb.org/en/stable/gen.html#tornado.gen.with_timeout) would works.

**Comment by kerma** [comment]
Yes, I did test manually with Python 3.4. Testing involved playing with connect setting connect_timeout to something low (like 2 seconds) and executing long running queries (_select sleep(5);_). The expected behavior was there for me.

**Comment by methane** [comment]
@kerma What is the expected behavior?
`connect_timeout` shouldn't affect to long running queries.

**Comment by methane** [comment]
I meant if you use `sock.settimeout()`, it is blocking IO and Tornado IO loop can't work while blocking.
"Timeout happens" is not enough test.  Check that ioloop works while waiting connect.

**Comment by kerma** [comment]
You are right, this sock.settimeout is blocking the Tornado IO loop.

I'll try to come up with something else.

**Pull request closed without merging**
